### ISSUE TITLE
Отсутствует операция деления

### ISSUE THREAD

**Issue by YegorMan** [yaroslav-hub/Calculator#1]
https://github.com/yaroslav-hub/Calculator/blob/4a41f160ad5d4290b1572e25f38f4450d779c299/Calculator/Program.cs#L17

**Comment by yaroslav-hub** [comment]
Добавил операцию целочисленного деления.

[Коммит с исправлением](https://github.com/yaroslav-hub/Calculator/commit/0a8ee8a39cfc4c8f89f0d537126b200c9ade2312)
